### ISSUE TITLE
编译报错，有没有现成的编译好的

### ISSUE THREAD

**Issue by Omoinemie** [zfile-dev/zfile-vue#64]
### nodejs 版本

16.16

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

npm-8.5.1

(推荐使用 `pnpm`)

<br />

### 系统

debian11

(该项目开发环境系统为 `win11`)

<br />
<br />

## bug

```
root@VM-0-13-ubuntu:~/zfile-vue# npm install

> zfile@4.0.10 prepare
> husky install

husky - Git hooks installed

up to date, audited 1163 packages in 6s

169 packages are looking for funding
  run `npm fund` for details

13 vulnerabilities (8 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
`root@VM-0-13-ubuntu:~/zfile-vue# npm run build

> zfile@4.0.10 build
> vite build

failed to load config from /root/zfile-vue/vite.config.ts
error during build:
TypeError: (0 , import_vite_plugin_svg_icons.createSvgIconsPlugin) is not a function
    at tov_default (/root/zfile-vue/vite.config.ts:225:59)
    at Object.<anonymous> (/root/zfile-vue/vite.config.ts:244:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.require.extensions.<computed> [as .ts] (/root/zfile-vue/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:61973:20)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (/root/zfile-vue/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:61981:17)
    at loadConfigFromFile (/root/zfile-vue/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:61900:32)
`
<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by zhaojun1998** [comment]
@Omoinemie 

我放到了 `releases` 页面：https://github.com/zfile-dev/zfile-vue/releases
