### ISSUE TITLE
编译报错 CentOS8.1

### ISSUE THREAD

**Issue by Uni9k** [zfile-dev/zfile-vue#66]
编译报错 CentOS8.1

[root@MiWiFi-RA74-srv zfile-vue-4.0.0]# npm run build

> zfile@4.1.0 build
> vite build

failed to load config from /root/disk/zfile-vue-4.0.0/vite.config.ts
error during build:
Error: The service was stopped: write EPIPE
    at /root/disk/zfile-vue-4.0.0/node_modules/esbuild/lib/main.js:1337:25
    at /root/disk/zfile-vue-4.0.0/node_modules/esbuild/lib/main.js:666:9
    at afterClose (/root/disk/zfile-vue-4.0.0/node_modules/esbuild/lib/main.js:644:7)
    at /root/disk/zfile-vue-4.0.0/node_modules/esbuild/lib/main.js:2050:11
    at onwriteError (node:internal/streams/writable:415:3)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)

**Comment by Uni9k** [comment]
win11环境编译成功。

**Comment by Uni9k** [comment]
win11环境编译成功。
